package saga.order.enums;

public enum OrderSagaEvent {
    START_ORDER,
    PAYMENT_SUCCESS,
    PAYMENT_FAILURE,
    INVENTORY_SUCCESS,
    INVENTORY_FAILURE,
    COMPLETE,
    INVENTORY_COMPENSATED,
    PAYMENT_COMPENSATED,
    PAYMENT_COMPENSATE_FAIL,
    INVENTORY_COMPENSATE_FAIL,
}
